### ISSUE TITLE
Stats page failing

### ISSUE THREAD

**Issue by AlexanderPico** [BiGCAT-UM/website-monitoring#14]
The critical information to test on this page is the content pulled in from generated stats files. I wonder if this is failing because it takes a few 100ms to load?  Not sure how the content check is done exactly, e.g., does it wait for page to load?

https://jenkins.bigcat.unimaas.nl/job/Website%20Monitoring/lastCompletedBuild/testReport/org.wikipathways/WikiPathwaysStatisticsPage/WebsiteContent/

**Comment by egonw** [comment]
See https://github.com/BiGCAT-UM/website-monitoring/issues/15
